.changes/unreleased/Fixed-20230110-092244.yaml
internal/gosrc/finder.go

Finder should use the GoFiles attribute to access the source files,
not CompiledGoFiles, which looks at the processed files.
This is a leftover of coding this against go/packages' NeedsSyntax,
which is supposed to be in the order of CompiledGoFiles.
Resolves #54

finder: Use GoFiles, not CompiledGoFiles

---

.changes/unreleased/Added-20230112-095400.yaml
docs/Makefile
docs/config.toml
docs/content/en/_index.md
docs/content/en/docs/_index.md
docs/content/en/docs/publish/github-pages.md
docs/content/en/docs/usage/_index.md
docs/content/en/docs/usage/usage.txt
docs/frontmatter.tmpl
flags.go
flags_test.go
generate.go
generate_test.go
help.go
integration_test.go
internal/html/render.go
internal/pathx/descend.go
internal/pathx/descend_test.go
main.go
main_test.go

Adds a -home flag which allows changing the home page
for the generated website.
With this, if you add `-home $importPath`,
then the landing page of the generated website
is the documentation for `$importPath`.
Resolves #58

Add -home flag

---

.changes/unreleased/Added-20230118-204543.yaml
internal/html/static/css/main.css
internal/html/tmpl/layout.html

Adds a *very small* footer
at the bottom of each page in standalone mode
that indicates that it was generated by doc2go.

standalone: Add a small "generated by" footer

---

.changes/unreleased/Added-20230119-193054.yaml
docs/Makefile
docs/content/en/docs/usage/config.md
docs/content/en/docs/usage/frontmatter.md
docs/content/en/docs/usage/highlight.md
docs/content/en/docs/usage/links.md
docs/embed.rc
docs/standalone.rc
flags.go
flags_test.go
go.mod
go.sum
help.go
help/config.txt
help/default.txt
main.go

Read configuration from a doc2go.rc using a very simple format
as defined in [ff.PlainParser][1].
[1]: https://pkg.go.dev/github.com/peterbourgon/ff/v3#PlainParser
The configuration path may be changed with the `-config` flag.
Flags that alter execution mode (version, help, print-css, list-themes)
are not allowed inside configuration files.
Using configuration files also simplifies the Makefile for docs
by putting more of the flags in there.
Resolves #8

Add configuration support

---

.github/workflows/release.yml
.goreleaser.yml

goreleaser does not update release notes
if changelog.skip is true
even if `--release-notes` is passed.
Drop it to resolve the issue.
Related: https://github.com/abhinav/stitchmd/pull/54
Also, --rm-dist has been deprecated in favor of --clean.
Related: https://github.com/abhinav/stitchmd/pull/53

ci/release: Fix release notes

---

go.mod
go.sum
integration_test.go

Use ring.Q instead of the inefficient slice-based queue.

integration_test: Use ring.Q

---

.golangci.yml
flags_test.go

Enabling t.Parallel for all tests is not a good idea after all.
Enabling it for slow tests makes sense, but not for all tests.

lint: Drop paralleltest

---

generate.go
internal/godoc/assemble.go
internal/gosrc/finder.go
internal/relative/relative.go
internal/slices/doc.go
internal/sliceutil/doc.go
internal/sliceutil/prefix.go
internal/sliceutil/prefix_test.go
internal/sliceutil/remove.go
internal/sliceutil/remove_test.go
internal/sliceutil/transform.go
internal/sliceutil/transform_test.go

Rename 'slices' to 'sliceutil' to allow use of the std 'slices' package
without import conflicts.

internal: Rename slices to sliceutil

---

integration/go.mod
integration/integration_test.go
internal/iotest/writer.go
internal/iotest/writer_test.go

This is a copy of what I've added to several other projects.
It reproduces the original input in the `t.Log` almost exactly.
The old version was also contractually incorrect:
it returned fewer bytes than were provided,
so the caller assumed a broken write.
This is why it wasn't usable with the integration test.
This remedies that as well.

iotest: Add a better, line-buffered writer

---

.github/workflows/ci.yml

The unit tests already verify that everything can be compiled
and the integration tests build the binary from scratch.
There's no need to `make build` separately in CI.

ci: Drop separate build step in tests

---

docs/Makefile
docs/assets/scss/_chroma.scss
docs/content/en/docs/usage/config-keys.txt
docs/content/en/docs/usage/config.md
flags.go
flags_test.go

List supported configuration keys in the documentation website.
Add a hidden -print-config-keys flag to do this.

docs: List supported configuration keys

---

.changes/unreleased/Fixed-20231110-202429.yaml
integration/integration_test.go
integration/testdata/self.json
integration/testdata/testify.json
integration/testdata/xnet.json
link.go
main.go

When we added support for -rel-link-style,
only links generated by the HTML package directly were updated.
We missed links generated inside code samples.
This fixes those links by plumbing RelLinkStyle to docLinker,
and using it to normalize them.
Adds an integration test to verify that all relative links
in the generated HTML have a trailing '/' with this flag
and can still be visited.
Resolves #154

Respect -rel-link-style=directory for code links

---

Makefile

On macOS, the default find does not have the -printf operator.
Use dirname to get the directory name instead.

make: 'find -printf' not supported everywhere

---

.changes/unreleased/Added-20231112-220506.yaml
docs/content/en/docs/embed/hugo.md
docs/content/en/docs/embed/jekyll.md
docs/content/en/docs/usage/frontmatter.md
docs/frontmatter.tmpl
internal/html/render.go
internal/html/render_test.go

Right now, frontmatter templates have to use this messy template
to pick the correct title for various cases:
title: "
{{- with .Package.Name -}}
{{ if ne . "main" }}{{ . }}{{ else }}{{ $.Basename }}{{ end }}
{{- else -}}
{{ with .Basename }}{{ . }}{{ else }}Reference{{ end }}
{{- end -}}
"
Add a `.Name` to the context that implements this logic
so that it may be shortened to:
title: "{{ .Name }}"
Resolves #70

frontmatter: Add '.Name' helper

---

.changes/unreleased/Changed-20231114-060755.yaml
internal/godoc/assemble.go
internal/godoc/assemble_test.go
internal/html/static/css/main.css
internal/html/static/js/permalink.js
internal/html/tmpl/package.html

Matching the behavior of pkg.go.dev,
if a type, function, or method is deprecated,
show it in a collapsed `<details>` section.
Resolves #19

Hide deprecated objects by default

---

.changes/unreleased/Added-20240119-155752.yaml
flags.go
flags_test.go
generate.go
help/default.txt
integration/integration_test.go
internal/html/render.go
main.go

Adds a `-subdir` flag to doc2go.
If specified, documentation will be generated under `$out/$sub`,
where `$out` is the output directory per `-out`.
Further, with this flag present,
we'll generate an index at `$out/index.html` of the siblings of `$sub`,
allowing this to generate versioned documentation.
For example:
git checkout v1.2.3
doc2go -subdir v1.2.3 ./...
git checkout v1.5.0
doc2go -subdir v1.5.0 ./...
This will result in a `_site/index.html` that points to
`_site/v1.2.3/` and `_site/v1.5.0/`, both of which have the full documentation
for the package at that point in time.
The static assets are shared between all websites.
Resolves #76

Add -subdir option for versioned documentation

---

.changes/unreleased/Fixed-20240119-231536.yaml
integration/integration_test.go
internal/html/render.go
internal/html/render_test.go

Current filter misses packages such as: go/internal/gcimporter.
This fixes filtering to ignore packages that are named internal,
inside internal, or contain /internal/.
Resolves #176

html/render: exhaustive internal handling

---

.changes/unreleased/Fixed-20240119-232009.yaml
internal/gosrc/finder.go
internal/gosrc/finder_test.go

We should not include vendored code in output.
This matches expected behavior in:
- https://pkg.go.dev/std
- https://godocs.io/std
Fixes #178

gosrc/finder: omit vendor packages

---

.changes/unreleased/Changed-20240120-203417.yaml
internal/html/render_test.go
internal/html/static/css/main.css
internal/html/tmpl/layout.html

In standalone mode, change the navbar to include a link
to the page's index.
Resolves #182

standalone/navbar: add link to index section

---

internal/html/static/css/main.css

otherwise it shifts the breadcrumbs to the middle

internal/html: make sure margin only applies to index link

---

.changes/unreleased/Added-20240121-152808.yaml
.changes/unreleased/Fixed-20240121-152840.yaml
internal/html/render.go
internal/html/render_test.go
internal/html/static/css/main.css
internal/html/tmpl/layout.html
internal/html/tmpl/package.html

Adds a link that goes to the root of the website to the navbar.
This link will point to the index.html inside OutDir, whatever that is.
By default, that's the top-level package listing.
With `-subdir`, that's the sibling directory listing.
In adding this, I discovered and fixed a bug
where an "Index" link would show even on directory listing pages
that had breadcrumbs.
Resolves #187

standalone/navbar: Add "Root" link

---

integration/integration_test.go
internal/html/render.go
internal/html/render_test.go

The 'Root' link was intended to go to the root of the documentation website,
but it did not respect `-home`.
With `-home`, it breaks out of the documentation website,
jumping as many levels as the length of `-home`.
Issue reported by @3052 here:
https://github.com/abhinav/doc2go/issues/187#issuecomment-1902763663
Fix the bug and add tests to verify this behavior in integration tests.

standalone: Fix 'Root' link

---

internal/html/static/css/main.css

current layout is ugly on mobile:
> ![ugly](https://github.com/abhinav/doc2go/assets/147215885/d0a88b0b-251b-4fa4-9927-3d728f915c5d)
compared to GoDocs, which wraps:
> ![wrap](https://github.com/abhinav/doc2go/assets/147215885/6b5aaffa-513c-4c0a-9916-47e562de9c96)
this fix adds wrapping:
> ![fix](https://github.com/abhinav/doc2go/assets/147215885/07a2b4fa-40c3-45ff-a097-362e4910612b)

internal/html/static/css: flex-wrap

---

.changes/unreleased/Added-20240123-205331.yaml
flags.go
generate.go
help/default.txt
internal/html/render.go
internal/html/tmpl/layout.html
internal/html/tmpl/package.html
main.go

this flag allows user to inject version number into HTML. default is disabled.
fixes https://github.com/abhinav/doc2go/issues/192

add -pkg-version

---

Makefile
flags.go
flags_test.go
generate.go
go.mod
go.sum
help.go
internal/errdefer/errdefer_test.go
internal/errdefer/example_test.go
internal/flagvalue/file_switch.go
internal/flagvalue/list.go
internal/flagvalue/list_test.go
internal/godoc/assemble.go
internal/godoc/assemble_test.go
internal/godoc/synopsis.go
internal/gosrc/decl.go
internal/gosrc/decl_test.go
internal/gosrc/ex_test.go
internal/gosrc/finder.go
internal/gosrc/parser.go
internal/highlight/highlight.go
internal/highlight/lex.go
internal/html/render.go
internal/html/render_test.go
internal/must/must.go
main.go
main_test.go

Use braces.dev/errtrace to instrument all error return sites.
Error traces are reported at failure with %+v.

Instrument errors with errtrace

---

.goreleaser.yml

brews.tap has been deprecated in favor of brews.repository.
Update the goreleaser configuration per
https://goreleaser.com/deprecations/#brewstap.

goreleaser: brews.tap -> brews.repository

---

.github/workflows/docs.yml
docs/content/en/docs/faq.md
docs/content/en/docs/publish/github-pages.md
docs/content/en/docs/usage/highlight.md

In the GitHub Pages deployment instructions,
explain how to add client-side search to the site.
Also adds an FAQ section to the documentation
intended to address common questions and issues.

doc: Search from GH Workflow, add FAQ

---

.changes/unreleased/Fixed-20240212-194229.yaml
integration/integration_test.go
internal/html/render.go
internal/html/render_test.go

When `-rel-link-style` is set to `directory`, the renderer is suffixing static asset links with `/` but these are file links that should not be suffixed.

html: Don't suffix static asset links with "/"

---

.changes/unreleased/Changed-20240221-073146.yaml
internal/html/render.go
internal/html/render_test.go
internal/html/tmpl/command.html
internal/html/tmpl/package.html
main.go

For main packages, the only consumable part is the command.
There's no need to include the documentation of exported types defined
in main packages, because it's impossible to import and consume them.
To do this, a new command.html template is introduced.
This allows removing command-specific special cases from the package.html.
Resolves #210

Don't render types and functions in main packages

---

docs/Makefile
docs/config.toml
docs/content/en/.gitignore
docs/doc.go
docs/tricks.rc
go.mod
go.sum
tools.go

Adds an example demonstrating the various features of godoc
with the godoc-tricks repository.
Thanks to @oliverpool for this sugggestion.
Resolves #197

docs: Add a godoc-tricks example

---

.github/workflows/docs.yml
docs/.gitignore
docs/Makefile
docs/content/en/.gitignore
docs/standalone.rc

The latest release of Hugo includes a change where
HTML pages inside contentDir are treated like regular pages.
This is fine for embedded pages, but for standalone pages we don't want
Hugo to attempt to post-process them.
Move standalone pages to static/ so they get published as-is.

Upgrade to latest Hugo

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
go.mod
integration/go.mod

Upgrade to Go 1.23, change CI to use go.mod for Go version.

Upgrade to Go 1.23

---

.changes/unreleased/Changed-20250827-190250.yaml
.goreleaser.yml
docs/content/en/docs/install/_index.md

Switch to v2 format for goreleaser config
and use casks instead of formulae for Homebrew tap.
(Formulae are being deprecated by goreleaser.)

goreleaser: switch to v2 format

---

.changes/unreleased/Fixed-20250827-215537.yaml
internal/highlight/tokenindex.go
internal/highlight/tokenindex_test.go

It's possible for TokenIndex.Interval to panic
if we're trying to capture trail text for a token
(because the end offset is in the middle of a token)
but the start of that token is at or after the requested end offset.
This will usually happen with chaotic whitespace.
The included unit test reproduces the panic without the fix.
Resolves #290

highlight: fix index panic on certain inputs
